POST http://localhost:8080/alunos/
content-type: application/json

{   
    "nome": "Buffet1",
    "rg": "321",
    "cpf": "12345678921"
}

###

GET  http://localhost:8080/alunos/
content-type: application/json

###

GET  http://localhost:8080/aluno/3
content-type: application/json

###

DELETE   http://localhost:8080/aluno/1
content-type: application/json

###

PATCH  http://localhost:8080/aluno/35
content-type: application/json

{   
    "nome": "Andre",
    "rg": "321654987",
    "cpf": "12345678921"
}

###

GET  http://localhost:8080/aluno/cpf/12345678901
content-type: application/json
