POST http://localhost:8080/alunos/
content-type: application/json

{   
    "nome": "Buffet",
    "rg": "321654987",
    "cpf": "12345678921"
}

###

GET  http://localhost:8080/alunos/
content-type: application/json

###

PUT http://localhost:9000/api/personalidade/4
content-type: application/json

{   
    "nome": "Nome Api Rest 2.0",
    "historia": "Historia Api Rest 2.0"
}